# Generated by Django 5.1.6 on 2025-03-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_review_created_at_alter_review_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
